#!/bin/bash

export LICENSE_ID=
export SPARCDIR=$VSC_SCRATCH_PROJECTS_BASE/apps/$VSC_INSTITUTE_CLUSTER/$VSC_ARCH_LOCAL$VSC_ARCH_SUFFIX/cryoSPARC
export CREDIT_ACCOUNT=
export SSD_PATH=${VSC_SCRATCH_NODE}

# Do not edit below
export PATH=${SPARCDIR}/cryosparc_master/bin:$PATH
